DROP TABLE TB_USER CASCADE CONSTRAINTS;

CREATE TABLE TB_USER(
                        ID NUMBER NOT NULL,
                        EMAIL VARCHAR2(1000),
                        PASSWORD VARCHAR2(1000),
                        USERNAME VARCHAR2(1000),
                        ROLE VARCHAR2(1000)
);

ALTER TABLE TB_USER ADD CONSTRAINT PK_USER_ID PRIMARY KEY(ID);
--ALTER TABLE TB_USER ADD CONSTRAINT UK_USER_EMAIL UNIQUE(EMAIL);

CREATE SEQUENCE SQ_USER
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;


CREATE TABLE TB_ROLES(
                         ID NUMBER NOT NULL,
                         NAME VARCHAR2(1000)
);

ALTER TABLE TB_ROLES ADD CONSTRAINT PK_ROLES_ID PRIMARY KEY(ID);

CREATE SEQUENCE SQ_ROLES
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;

INSERT INTO TB_ROLES(id, name) VALUES(SQ_ROLE.NEXTVAL, 'ROLE_USER');
INSERT INTO TB_ROLES(id, name) VALUES(SQ_ROLE.NEXTVAL, 'ROLE_MODERATOR');
INSERT INTO TB_ROLES(id, name) VALUES(SQ_ROLE.NEXTVAL, 'ROLE_ADMIN');

COMMIT;