OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'C:\Users\Mingu\Desktop\»õ Æú´õ\TB_FAQ_DATA_TABLE.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "TB_FAQ"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"ID" ,
"TITLE" CHAR (500),
"CONTENT" CHAR (1000),
"WRITER" CHAR (255),
"DELETE_YN" CHAR (1),
"INSERT_TIME" CHAR (255),
"UPDATE_TIME" CHAR (255),
"DELETE_TIME" CHAR (255))
