--------------------------------------------------------
--  DDL for Table TB_PRODUCT
--------------------------------------------------------

  CREATE TABLE "TB_PRODUCT" ("ID" NUMBER, "TITLE" VARCHAR2(100), "DESCRIPTION" VARCHAR2(500), "PRICE" NUMBER, "DISCOUNT" NUMBER, "SALE_YN" CHAR(1), "DELETE_YN" CHAR(1) DEFAULT 'N', "INSERT_TIME" VARCHAR2(20), "UPDATE_TIME" VARCHAR2(20), "DELETE_TIME" VARCHAR2(20), "PERCENT" NUMBER, "CATEGORY" VARCHAR2(10), "NAME" VARCHAR2(1000), "TYPE" VARCHAR2(1000), "DATA" BLOB, "MODEL" VARCHAR2(100))
