OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'C:\Users\Mingu\Desktop\»õ Æú´õ\TB_ROLES_DATA_TABLE.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "TB_ROLES"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"ID" ,
"NAME" CHAR (1000))
