--유저테이블 생성 삭제
DROP TABLE TB_USER CASCADE CONSTRAINTS;

CREATE TABLE TB_USER (
    ID          NUMBER
    ,EMAIL       VARCHAR2(1000)
    ,PASSWORD    VARCHAR2(1000)
    ,USERID      VARCHAR2(1000)
    ,ROLE        VARCHAR2(1000)
    ,NAME        VARCHAR2(1000)
    ,BIRTH       VARCHAR2(1000)
    ,ADDRESS     VARCHAR2(1000)
    ,PHONE       VARCHAR2(1000)
    ,DELETE_YN   CHAR(1) DEFAULT 'N'
    ,INSERT_TIME VARCHAR2(1000)
    ,UPDATE_TIME VARCHAR2(1000)
    ,DELETE_TIME VARCHAR2(1000)
    ,CONSTRAINT "PK_USER_ID" PRIMARY KEY ( "ID" )
    ,CONSTRAINT "UK_USER_USERID" UNIQUE ( "USERID" )
    ,CONSTRAINT "UK_USER_EMAIL" UNIQUE ( "EMAIL" )
);

--시퀀스 생성
DROP SEQUENCE SQ_USER;

CREATE SEQUENCE SQ_USER INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 99999999;

--권한 테이블 생성
CREATE TABLE TB_ROLES (
    ID   NUMBER
    ,NAME VARCHAR2(1000)
    ,CONSTRAINT "PK_ROLES_ID" PRIMARY KEY ( "ID" )
);

--권한 테이블 시퀀스 생성
CREATE SEQUENCE SQ_ROLES INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 99999999;

INSERT INTO TB_ROLES (
    ID
    ,NAME
) VALUES (
    SQ_ROLES.NEXTVAL
   ,'ROLE_USER'
);

INSERT INTO TB_ROLES (
    ID
    ,NAME
) VALUES (
    SQ_ROLE.NEXTVAL
   ,'ROLE_MODERATOR'
);

INSERT INTO TB_ROLES (
    ID
    ,NAME
) VALUES (
    SQ_ROLES.NEXTVAL
   ,'ROLE_ADMIN'
);

COMMIT;