--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-27-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_USER_JWT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TB_USER_JWT" 
   (	"ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"USERNAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSWORD" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"BIRTH" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ROLES" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"DELETE_YN" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"INSERT_TIME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATE_TIME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"DELETE_TIME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_USER_ID_JWT
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_USER_ID_JWT" ON "ADMIN"."TB_USER_JWT" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UK_USER_USERNAME_JWT
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."UK_USER_USERNAME_JWT" ON "ADMIN"."TB_USER_JWT" ("USERNAME") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TB_USER_JWT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TB_USER_JWT" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TB_USER_JWT" ADD CONSTRAINT "PK_USER_ID_JWT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "ADMIN"."TB_USER_JWT" ADD CONSTRAINT "UK_USER_USERNAME_JWT" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
