  CREATE TABLE "TB_BOARD" 
   (	"TITLE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTENT" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"WRITER" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"DELETE_YN" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N' NOT NULL ENABLE, 
	"VIEW_CUT" NUMBER, 
	"NOTICE_YN" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"SECRET_YN" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"DELETE_TIME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATE_TIME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"INSERT_TIME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"DATA" BLOB, 
	"TYPE" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("DATA") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;