
  CREATE TABLE "TB_FAQ" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TITLE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTENT" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"WRITER" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"DELETE_YN" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"INSERT_TIME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATE_TIME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"DELETE_TIME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

