
  CREATE TABLE "TB_PRODUCT" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MODEL" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"PRICE" NUMBER, 
	"DISCOUNT" NUMBER, 
	"SALE_YN" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"DELETE_YN" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"INSERT_TIME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATE_TIME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"DELETE_TIME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PERCENT" NUMBER, 
	"CATEGORY" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"TYPE" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"DATA" BLOB, 
	 CONSTRAINT "PK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("DATA") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

