
  CREATE TABLE "TB_REVIEW" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"REVIEW_ID" NUMBER, 
	"NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"WRITER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTENT" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"TITLE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"INSERT_TIME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATE_TIME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"DELETE_TIME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"DELETE_YN" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"TYPE" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"DATA" BLOB, 
	"STAR_NUM" NUMBER, 
	 CONSTRAINT "PK_REVIEW_ID" PRIMARY KEY ("REVIEW_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE, 
	 CONSTRAINT "FK_ID" FOREIGN KEY ("ID")
	  REFERENCES "TB_PRODUCT" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("DATA") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

