
  CREATE TABLE "TB_USER_CART" 
   (	"ID" NUMBER, 
	"EMAIL" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSWORD" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"USERNAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"ROLE" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"BIRTH" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONE" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"DELETE_YN" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"INSERT_TIME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATE_TIME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"DELETE_TIME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

