CREATE TABLE TB_USER_JWT (
    ID          VARCHAR2(255)
    ,USERNAME    VARCHAR2(255) NOT NULL 
    ,PASSWORD    VARCHAR2(256)
    ,NAME        VARCHAR2(256)
    ,BIRTH       VARCHAR2(256)
    ,EMAIL       VARCHAR2(255)
    ,ADDRESS     VARCHAR2(1000)
    ,PHONE       VARCHAR2(100)
    ,GENDER      VARCHAR2(10)
    ,ROLES       VARCHAR2(255)
    ,DELETE_YN   CHAR(1) DEFAULT 'N'
    ,INSERT_TIME VARCHAR2(255)
    ,UPDATE_TIME VARCHAR2(255)
    ,DELETE_TIME VARCHAR2(255)
    ,CONSTRAINT "PK_USER_ID_JWT" PRIMARY KEY ( "ID" )
    ,CONSTRAINT "UK_USER_USERNAME_JWT" UNIQUE( "USERNAME" )
);

CREATE SEQUENCE SQ_USER MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;

DROP TABLE TB_USER_JWT;