OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'C:\Users\Mingu\Desktop\utf-8\TB_CATEGORY_DATA_TABLE.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "TB_CATEGORY"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"CATEGORY" CHAR (30),
"NO" CHAR (10))
