--------------------------------------------------------
--  파일이 생성됨 - 목요일-8월-04-2022   
--------------------------------------------------------
@C:\Users\Mingu\Desktop\utf-8\GOODS_SEQ.sql
@C:\Users\Mingu\Desktop\utf-8\SQ_BOARD.sql
@C:\Users\Mingu\Desktop\utf-8\SQ_CART.sql
@C:\Users\Mingu\Desktop\utf-8\SQ_FAQ.sql
@C:\Users\Mingu\Desktop\utf-8\SQ_FILES.sql
@C:\Users\Mingu\Desktop\utf-8\SQ_LIKE.sql
@C:\Users\Mingu\Desktop\utf-8\SQ_ORDER.sql
@C:\Users\Mingu\Desktop\utf-8\SQ_PRODUCT.sql
@C:\Users\Mingu\Desktop\utf-8\SQ_REVIEW.sql
@C:\Users\Mingu\Desktop\utf-8\SQ_ROLES.sql
@C:\Users\Mingu\Desktop\utf-8\SQ_TUTORIAL.sql
@C:\Users\Mingu\Desktop\utf-8\SQ_USER.sql
@C:\Users\Mingu\Desktop\utf-8\SQ_USER_CART.sql
@C:\Users\Mingu\Desktop\utf-8\TB_CART.sql
@C:\Users\Mingu\Desktop\utf-8\TB_CATEGORY.sql
@C:\Users\Mingu\Desktop\utf-8\TB_FAQ.sql
@C:\Users\Mingu\Desktop\utf-8\TB_LIKE.sql
@C:\Users\Mingu\Desktop\utf-8\TB_ORDER.sql
@C:\Users\Mingu\Desktop\utf-8\TB_PRODUCT.sql
@C:\Users\Mingu\Desktop\utf-8\TB_REVIEW.sql
@C:\Users\Mingu\Desktop\utf-8\TB_ROLES.sql
@C:\Users\Mingu\Desktop\utf-8\TB_USER.sql
--@C:\Users\Mingu\Desktop\utf-8\TB_CATEGORY_DATA_TABLE.ldr
--@C:\Users\Mingu\Desktop\utf-8\TB_CATEGORY_DATA_TABLE.ctl
--@C:\Users\Mingu\Desktop\utf-8\TB_FAQ_DATA_TABLE.ldr
--@C:\Users\Mingu\Desktop\utf-8\TB_FAQ_DATA_TABLE.ctl
--@C:\Users\Mingu\Desktop\utf-8\TB_PRODUCT_DATA_TABLE.ldr
--@C:\Users\Mingu\Desktop\utf-8\TB_PRODUCT_DATA_TABLE.ctl
--@C:\Users\Mingu\Desktop\utf-8\TB_ROLES_DATA_TABLE.ldr
--@C:\Users\Mingu\Desktop\utf-8\TB_ROLES_DATA_TABLE.ctl
--@C:\Users\Mingu\Desktop\utf-8\TB_USER_DATA_TABLE.ldr
--@C:\Users\Mingu\Desktop\utf-8\TB_USER_DATA_TABLE.ctl
@C:\Users\Mingu\Desktop\utf-8\TB_CART_CONSTRAINT.sql
@C:\Users\Mingu\Desktop\utf-8\TB_FAQ_CONSTRAINT.sql
@C:\Users\Mingu\Desktop\utf-8\TB_LIKE_CONSTRAINT.sql
@C:\Users\Mingu\Desktop\utf-8\TB_ORDER_CONSTRAINT.sql
@C:\Users\Mingu\Desktop\utf-8\TB_PRODUCT_CONSTRAINT.sql
@C:\Users\Mingu\Desktop\utf-8\TB_REVIEW_CONSTRAINT.sql
@C:\Users\Mingu\Desktop\utf-8\TB_ROLES_CONSTRAINT.sql
@C:\Users\Mingu\Desktop\utf-8\TB_USER_CONSTRAINT.sql
@C:\Users\Mingu\Desktop\utf-8\TB_CART_REFCONSTRAINT.sql
@C:\Users\Mingu\Desktop\utf-8\TB_LIKE_REFCONSTRAINT.sql
@C:\Users\Mingu\Desktop\utf-8\TB_ORDER_REFCONSTRAINT.sql
@C:\Users\Mingu\Desktop\utf-8\TB_REVIEW_REFCONSTRAINT.sql
